//! Generates the umbrella C header consumed by `addTranslateC`.
//!
//! Walks the vendored lexbor source tree and emits one `#include` per public
//! header, in a deterministic (sorted) order.
//!
//! Translation-unit-private static data tables are excluded:
//!   * `res.h`
//!   * `*_res.h`
//! They are not self-contained (they reference declarations from sibling
//! headers and depend on a specific include order) and are only ever included
//! by lexbor's own `.c` files.
//!
//! Usage: gen-c-header <lexbor-source-dir> <output-file>

const std = @import("std");

pub fn main(init: std.process.Init) !void {
    const gpa = init.gpa;
    const io = init.io;
    const arena = init.arena.allocator();

    const args = try init.minimal.args.toSlice(arena);
    if (args.len != 3) {
        try std.Io.File.stderr().writeStreamingAll(
            io,
            "usage: gen-c-header <lexbor-source-dir> <output-file>\n",
        );
        return error.BadUsage;
    }
    const src_dir = args[1];
    const out_path = args[2];

    var dir = try std.Io.Dir.cwd().openDir(io, src_dir, .{ .iterate = true });
    defer dir.close(io);

    var walker = try dir.walk(gpa);
    defer walker.deinit();

    var includes: std.ArrayList([]const u8) = .empty;
    defer includes.deinit(gpa);

    while (try walker.next(io)) |entry| {
        if (entry.kind != .file) continue;
        if (!std.mem.startsWith(u8, entry.path, "lexbor/")) continue;
        if (!std.mem.endsWith(u8, entry.path, ".h")) continue;
        if (std.mem.eql(u8, entry.basename, "res.h")) continue;
        if (std.mem.endsWith(u8, entry.basename, "_res.h")) continue;

        const dup = try arena.dupe(u8, entry.path);
        std.mem.replaceScalar(u8, dup, '\\', '/');
        try includes.append(gpa, dup);
    }

    std.mem.sort([]const u8, includes.items, {}, lessThanStr);
    if (includes.items.len == 0) {
        try std.Io.File.stderr().writeStreamingAll(
            io,
            "gen-c-header: no public headers found; is the vendored tree present?\n",
        );
        return error.NoHeadersFound;
    }

    var buf: std.ArrayList(u8) = .empty;
    defer buf.deinit(gpa);

    try buf.appendSlice(gpa, header_preamble);
    for (includes.items) |inc| {
        try buf.appendSlice(gpa, "#include <");
        try buf.appendSlice(gpa, inc);
        try buf.appendSlice(gpa, ">\n");
    }
    try buf.appendSlice(gpa, "\n#endif /* Z_LEXBOR_SYS_C_H */\n");

    try std.Io.Dir.cwd().writeFile(io, .{ .sub_path = out_path, .data = buf.items });
}

fn lessThanStr(_: void, a: []const u8, b: []const u8) bool {
    return std.mem.lessThan(u8, a, b);
}

const header_preamble =
    \\/* GENERATED by tools/gen_c_header.zig -- DO NOT EDIT. */
    \\/*
    \\ * Umbrella header over every public lexbor header.
    \\ *
    \\ * Translation-unit-private static data tables (`res.h` and `*_res.h`) are
    \\ * deliberately excluded: they are not self-contained (they depend on
    \\ * declarations from sibling headers and on a specific include order) and
    \\ * are only ever included by lexbor's own .c files.
    \\ */
    \\#ifndef Z_LEXBOR_SYS_C_H
    \\#define Z_LEXBOR_SYS_C_H
    \\
    \\
;
